### PR TITLE
Adding ability to handle a program parameter

### PR DESCRIPTION
**Pull request by rubailly**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rubailly did you intentionally commit changes in the .project and .classpath files?

**Comment by rubailly** [comment]
@dkayiwa -Nop, it wasn't intentional. It looks like they are supposed to be ignored:  [.gitignore](https://github.com/openmrs/openmrs-module-rowperpatientreports/blob/master/.gitignore) .
Let me check this and create a new pull request.

**Comment by dkayiwa** [comment]
@rubailly are you still working on this? :)

**Comment by rubailly** [comment]
I'm closing this pull request. The problems was on my local dev env. 
I got it solved after running 
`git rm -r --cached
`
It's a few changes I made, I'll check out the code again and make a new pull request.

**Pull request closed without merging**
